### ISSUE TITLE
voodoo lady/ scummbar

### ISSUE THREAD

**Issue by remdwaas** [Shoopity/MonkeyIslandPinball#28]
check if it's possible to disable a mode after completing it, but this has to be still decided. for the LeChuck items it's a must, because that is for the escape mode.

**Comment by Shoopity** [comment]
As of today, you play each mode once only.  When you've completed all the modes for the Voodoo lady, shooting her shot acts as though she's locked.  I'll go ahead and close the issue, but I think I still need to do some work to prevent unlocking her again.
The Bar works the same way, but I'm pretty sure once the Bar closes, you can't open it again.
I'll take a look at the LeChuck items, but I'm don't currently see how they're _supposed_ to work.  I don't see anything calling StartLechuckItemsSlotmachine().  Is that supposed to happen when the Le Chuck shot is made?
